### ISSUE TITLE
Issue uploading to aws : Failed to open TCP connection

### ISSUE THREAD

**Issue by adamskriger** [thoughtbot/paperclip#2159]
![image](https://cloud.githubusercontent.com/assets/16260612/14188589/5545a430-f757-11e5-93fd-e8783bc381b1.png)

Followed the conversation that occurred in issue #2021 to make sure paperclip worked with aws-sdk > 2.0 

But am now running into this connection issue when uploading and am not sure which configuration issue might be triggering this? 

```
development.rb
  config.paperclip_defaults = {
    :storage => :s3,
    :s3_region => 'us-standard',
    :s3_credentials => {
      :bucket => ENV['S3_BUCKET_NAME'],
      :access_key_id => ENV['AWS_ACCESS_KEY_ID']
    }
  }

  Paperclip.options[:command_path] = "/usr/local/bin/"
```

```
  development:
     access_key_id: '...'
     secret_access_key: '...'
  production:
     access_key_id: '...'
     secret_access_key: '....'
```
