### ISSUE TITLE
Seahorse::Client::NetworkingError: Failed to open TCP connection to bucket.s3.southeast-1.amazonaws.com:443 (getaddrinfo: Name or service not known)

### ISSUE THREAD

**Issue by heaven** [thoughtbot/paperclip#2263]
Paperclip is configured as follows:
```yaml
staging:
  images:
    storage: 's3'
    bucket: 'bucket'
    url: ':s3_alias_url'
    path: '/attachments/images/:assetable/:id_partition/:style/:basename:dotextension'
    default_url: '//qwerty.cloudfront.net/assets/missing/:assetable/:style.jpg'
    default_style: 'original'
    s3_region: 'southeast-1'
    s3_protocol: ''
    s3_host_alias: 'qwerty.cloudfront.net'
    s3_credentials:
      <<: *s3_credentials

  files:
    storage: 's3'
    bucket: 'bucket'
    url: ':s3_domain_url'
    path: '/attachments/files/:assetable/:id_partition/:basename:dotextension'
    s3_region: 'southeast-1'
    s3_protocol: ''
    s3_credentials:
      <<: *s3_credentials
```

In the AWS console I see `Endpoint: bucket.s3-website-ap-southeast-1.amazonaws.com` so I tried to set `s3_host_name` to `s3-website-ap-southeast-1.amazonaws.com`, but paperclip didn't use it.
