### ISSUE TITLE
Using Paperclip 5 with Ceph (or other S3-compatible alternative)

### ISSUE THREAD

**Issue by RISCfuture** [thoughtbot/paperclip#2267]
I had a working Paperclip 4 configuration that used a custom endpoint (our internal Ceph install), but it's broken now in Paperclip 5 because of AWS-SDK v2's requirement to specify a region. It looks like from the docs specifying the `endpoint` option to `Aws.config` overrides whatever region you set, but I suppose you still need to set a region anyway? I'm not sure. Also not sure how this translates to Paperclip options. Here's my current, not-working options:

```` yaml
---
storage: :s3
s3_protocol: :https
s3_host_name: s3.mydomain.com
s3_endpoint: s3.mydomain.com
s3_region: us-west-2 # must be specified?
url: ":s3_domain_url"
s3_credentials:
  [...]
  bucket: go-media-staging
````

When I turn on HTTP wire trace, you can see that it still tries to connect to the Amazon endpoint:

````
opening connection to go-media-staging.s3-us-west-2.amazonaws.com:443...
````

**Comment by RISCfuture** [comment]
Figured it out after much effort. You have to separately configure the AWS Resource object and the Paperclip interpolation options. Here's a working config:

```` yaml
---
storage: :s3
path: "[...]"
s3_region: us-west-2 # ignored
s3_protocol: :https # for paperclip interpolation, ignored by aws-sdk
s3_host_name: s3.mydomain.com # for paperclip interpolation
url: ":s3_path_url" # for paperclip interpolation (required for ceph)
s3_options:
  endpoint: "https://s3.mydomain.com" # for aws-sdk
  force_path_style: true # for aws-sdk
  signature_version: s3 # ceph doesnt support v4 auth
s3_credentials:
  [...]
  bucket: your-bucket
````
