### ISSUE TITLE
Conflict with existing AWS account

### ISSUE THREAD

**Issue by K1N5L4Y3R** [thoughtbot/paperclip#2277]
Hi,

**Before** I included Paperclip (amazing gem :thumbsup:) to my project, I wrote a job that uses S3 for listing and downloading objects from a bucket from an AWS account (let's call it **Account A**). This was made via a config/initializers/aws.rb with the following:

```
# config/initializers/aws.rb
require 'aws-sdk'

Aws.config.update({
  region: ENV['ACCOUNT_A_REGION'],
  credentials: Aws::Credentials.new(ENV['ACCOUNT_A_ACCESS_KEY'], ENV['ACCOUNT_A_SECRET_ACCESS_KEY'])
})
```
This worked as expected.

Then, I included Paperclip and want to store attachments in another AWS account (let's call it **Account B**). I tried to configure Paperclip as per the documentation:

```
# config/application.rb
config.paperclip_defaults = {
      storage: :s3,
      s3_region: ENV['ACCOUNT_B_REGION'],
      s3_credentials: YAML.load(ERB.new(File.read("#{Rails.root}/config/s3.yml")).result)["s3"][Rails.env].symbolize_keys!,
      # url: ':s3_domain_url',
      # path: ':class/:attachment/:id/:style/:filename',
      # s3_protocol: "https",
    }
```

```
# config/s3.yml
s3:
  defaults: &defaults
    access_key_id: <%= ENV['ACCOUNT_B_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['ACCOUNT_B_SECRET_ACCESS_KEY'] %>
    s3_region: <%= ENV['ACCOUNT_B_REGION'] %>,
    # profile_name: s3
    # s3_host_name: s3.amazonaws.com
  development:
    <<: *defaults
    bucket: "xxx-development"
  test:
    <<: *defaults
    bucket: "xxx-test"
  production:
    <<: *defaults
    bucket: "xxx-production"
```

When I did this I got an "Access Denied Error". I made tests with the Account B by itself to check if it had permission (with S3 Browser, and in an IRB console) and the tests succeded, so I figured out that there was a **conflict between the two accounts**.
To confirm this, I commented config/initializers/aws.rb (and didn't run the job that depends on the Account A). This time, Paperclip worked.

**Conclusion:** When there is already a config/initializers/aws.rb file with an Account A, Paperclip is not able to use an Account B even if Paperclip::Attachment.default_options include the details for it. It will use the Account A.

Is there a way around this?

Thank you.
