### ISSUE TITLE
Using PaperClip with FakeS3

### ISSUE THREAD

**Issue by rdeavila** [thoughtbot/paperclip#2354]
Hi! I'm trying to use paperclip with fakes3, in development and test environments. But, all endpoint and port configurations are ignored; paperclip always try to use `amazonaws.com:443`. Fakes3 use plain http.

I have tried change `url`, `s3_host_name` and `s3_host_alias` to `s3:4567`, but without success. (`s3` is the fakes3 hostname inside my docker container).

What I'm doing wrong?

**Comment by samstickland** [comment]
I have the same problem. I had the configuration working with Paperclip 4.x and AWS-v1, but in all the configuration rejigging moving to 5.1.0 and the regular aws gem it now no longer works, and I can't figure out why.

I have this in an initializer:

```
  paperclip_defaults = Rails.application.config_for :paperclip
  paperclip_defaults.symbolize_keys!

  Paperclip::Attachment.default_options.merge! paperclip_defaults
```

And this in `config/paperclip.yml`:

```
  test:
      storage:       :s3
      bucket:        "test"
      s3_host_name:  "localhost"
      s3_host_alias: "localhost:10001/test"
      url:           ":s3_alias_url"
      s3_protocol:   'http'
      s3_credentials:
        access_key_id:       "abc"
        secret_access_key:   "abc"
        s3_endpoint:         "localhost"
        s3_port:             10001
        s3_force_path_style: true
        use_ssl:             false
        s3_region:           "local"
```

However I'm just getting this error:

```
     Aws::Errors::NoSuchEndpointError:
       Encountered a `SocketError` while attempting to connect to:

         https://test.s3.local.amazonaws.com/test/users/cvs/1_test.pdf
```

It seems to simply be ignoring the `s3_alias_url` configuration.

Any ideas what I am doing wrong? I've already spent several hours digging around the codebase and trying various breakpoints, but I just don't seem to be making any headway

**Comment by trusche** [comment]
Same problem here. Paperclip used to work seamlessly with fake-s3 around a year ago, but I can't get it to work with current versions for the life of me. If anyone has any insights, it would be highly appreciated!

**Comment by trusche** [comment]
Figured it out, it works by using the (undocumented?) `s3_options` setting. It's also crucial to make sure those setting all have symbols as key, not strings, so I'm using `deep_symbolize_keys` instead of just `symbolize_keys` in the initializer (or you could just use symbols in the config file).

```
# config/initializers/paperclip.rb
paperclip_defaults = Rails.application.config_for :paperclip
paperclip_defaults.deep_symbolize_keys!
Paperclip::Attachment.default_options.merge! paperclip_defaults

# application.rb
    ...
    config.paperclip = config_for :paperclip
    ...

# config/paperclip.yml
development:
  storage: :s3
  s3_options:
    endpoint: http://localhost:10001
    force_path_style: true
  s3_credentials:
    bucket: mybucket
    access_key_id: foo
    secret_access_key: bar
  s3_region: eu-west-1
  s3_permissions: private
  path: "/development/:id_partition/:updated_at/:filename"
  url: ":s3_alias_url"
  default_url: /images/:style/missing.png
```
