### ISSUE TITLE
Paperclip 2.3.4 breaks S3 uploading

### ISSUE THREAD

**Issue by dmarkow** [thoughtbot/paperclip#326]
Using Rails 3.0.0 and Ruby 1.9.2, upgrading from paperclip 2.3.3 to 2.3.4 broke my S3 uploading. Looking at the logs, everything seems to work fine, but the file never actually makes it onto S3 and results in a broken link on my site.

My model:

```
class Projectdocument < ActiveRecord::Base
    belongs_to :project
    has_attached_file :attachment,
        :storage => :s3,
        :s3_credentials => Rails.root.join("config/s3.yml"),
        :path => "/projectdocuments/:attachment/:id/:basename.:extension"
end
```

My S3.yml

```
development:
    access_key_id: [my access key]
    secret_access_key: [my secret access key]
    bucket: pfcs_dev
production:
    access_key_id: [my access key]
    secret_access_key: [my secret access key]
    bucket: pfcs_production
```

Paperclip logs the following into my development.log, appearing to work fine. But when I look at my S3 account, the file doesn't get uploaded. Reverting to paperclip 2.3.3 instantly fixes the issue.

```
[paperclip] Saving attachments.
[paperclip] saving /projectdocuments/attachments/6228/Test File.txt
```

(Sorry for the duplicate issue, I accidentally closed my other one).
