### ISSUE TITLE
AWS::S3::Errors::SignatureDoesNotMatch

### ISSUE THREAD

**Issue by dbachet** [thoughtbot/paperclip#817]
I'm migrating my app from Rails 3.0.9 to 3.2.3 / ruby 1.9.3. I was using paperclip(2.3.11) with aws-s3 gem to store my pictures.

Now I want to use the last version of paperclip(3.0.1) with aws-sdk gem.

When trying to upload a file, I get the error: 

`AWS::S3::Errors::SignatureDoesNotMatch`
`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

It's creating the original style image on the S3 bucket, but not the other styles.

Here is also what I get from console: 

```
    [paperclip] Saving attachments.
    [paperclip] saving /presentation_pictures/43/original/Image_1.png
    [AWS S3 200 0.813272 0 retries] put_object(:acl=>:public_read,:bucket_name=>"*******_dev",:content_type=>"image/png",:data=>#<Paperclip::UploadedFileAdapter:0x2e144b4 @target=#<ActionDispatch::Http::UploadedFile:0x2dbb1fc @original_filename="Image 1.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"presentation_picture[picture]\"; filename=\"Image 1.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<File:/var/folders/tb/tbmv4LE9EwGNPr1QqU2S0E+++TI/-Tmp-/RackMultipart20120407-33502-1gajfe9>>, @tempfile=#<File:/var/folders/tb/tbmv4LE9EwGNPr1QqU2S0E+++TI/-Tmp-/Image 1.png20120407-33502-an4dcy>>,:key=>"presentation_pictures/43/original/Image_1.png")
```

A downgrade to paperclip 3.0.0 solved the problem. That made me think that it can be a paperclip issue ? :s

So I write here :)

I've set my aws.yml file as:

```
    development: &development
      bucket: bucket_name_for_dev
      access_key_id: *****
      secret_access_key: *******
    staging:
      <<: *development
      bucket: bucket_name_for_staging

    production:
      <<: *development
      bucket: bucket_name_for_prod
```

my model contains :

```
    has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "50x50>" }, :default_url => 'picture_missing.png',
         :storage => :s3,
         :bucket => "bucket_name_for_dev",
         :s3_credentials => Rails.root.join("config/aws.yml"),
         :path => "/presentation_pictures/:id/:style/:filename",
         :url  => ":s3_eu_url"

    attr_accessible :picture
    attr_accessor :picture_url
```

I'll stick to 3.0.0, then it's not a prior problem to me. But if I can help you, don't hesitate to ask me information if you think it's a paperclip issue. 

Today, I'm not able to launch tests as... I don't know how :/ But I could try!

Issue happened with: 

Ruby 1.9.3p125
Rails 3.2.3
ImageMagick 6.6.9-4
paperclip 3.0.1
aws-sdk 1.3.9
nokogiri 1.4.7

Thx a lot for your job!
