### ISSUE TITLE
Get AWS::S3::NoConnectionEstablished (AWS::S3::NoConnectionEstablished) when using S3 for storage 

### ISSUE THREAD

**Issue by joshcutler** [thoughtbot/paperclip#82]
```
AWS::S3::NoConnectionEstablished (AWS::S3::NoConnectionEstablished):
  /usr/local/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/connection.rb:213:in `connection'
  /usr/local/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/base.rb:69:in `request'
  /usr/local/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/base.rb:88:in `put'
  /usr/local/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/object.rb:241:in `store'
  app/controllers/admin/events_controller.rb:32:in `update'
  haml (2.0.9) lib/sass/plugin/rails.rb:19:in `process'
```

The plugin is working correctly with the local filesystem.  Also the s3.yml file is formatted like so:

``` yaml
development:
  access_key_id: some_number
  secret_access_key: some_other_number  
  bucket: dev-bucket
production:
  access_key_id: number
  secret_access_key:  some_other_number
  bucket: prod-bucket
```

This is how it is being used in the model:

``` ruby
has_attached_file :image, 
    :styles => { :medium => "300x300>", :thumb => "100x100>", :small_thumb => "50x50"},
    :storage => :s3,
    :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
    :s3_headers => {"Expires" => 1.year.from_now.httpdate},
    :path => ":class/:id/:attachment/:style.:extension"
```

Also I have tested connecting to S# via the aws/s3 console and can do so with no problems.  I can provide more information as needed.
